# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

DEPLOYGATE_API_TOKEN = ""
DEPLOYGATE_USER      = ""

default_platform :ios

platform :ios do
  lane :beta do
    gym(export_method: "ad-hoc")
    deploygate(api_token: DEPLOYGATE_API_TOKEN,
               user: DEPLOYGATE_USER,
               message: "fastlane study test message")
  end
end
